/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI description (this document) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    id?: components["parameters"]["rowFilter.users.id"];
                    email?: components["parameters"]["rowFilter.users.email"];
                    display_name?: components["parameters"]["rowFilter.users.display_name"];
                    avatar_url?: components["parameters"]["rowFilter.users.avatar_url"];
                    is_onboarded?: components["parameters"]["rowFilter.users.is_onboarded"];
                    raw_user_meta_data?: components["parameters"]["rowFilter.users.raw_user_meta_data"];
                    created_at?: components["parameters"]["rowFilter.users.created_at"];
                    updated_at?: components["parameters"]["rowFilter.users.updated_at"];
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                    /** @description Ordering */
                    order?: components["parameters"]["order"];
                    /** @description Limiting and Pagination */
                    offset?: components["parameters"]["offset"];
                    /** @description Limiting and Pagination */
                    limit?: components["parameters"]["limit"];
                };
                header?: {
                    /** @description Limiting and Pagination */
                    Range?: components["parameters"]["range"];
                    /** @description Limiting and Pagination */
                    "Range-Unit"?: components["parameters"]["rangeUnit"];
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferCount"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["users"][];
                        "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["users"][];
                        "application/vnd.pgrst.object+json": components["schemas"]["users"][];
                        "text/csv": components["schemas"]["users"][];
                    };
                };
                /** @description Partial Content */
                206: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: {
                    /** @description Filtering Columns */
                    select?: components["parameters"]["select"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferPost"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["users"];
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: {
                    id?: components["parameters"]["rowFilter.users.id"];
                    email?: components["parameters"]["rowFilter.users.email"];
                    display_name?: components["parameters"]["rowFilter.users.display_name"];
                    avatar_url?: components["parameters"]["rowFilter.users.avatar_url"];
                    is_onboarded?: components["parameters"]["rowFilter.users.is_onboarded"];
                    raw_user_meta_data?: components["parameters"]["rowFilter.users.raw_user_meta_data"];
                    created_at?: components["parameters"]["rowFilter.users.created_at"];
                    updated_at?: components["parameters"]["rowFilter.users.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: {
                    id?: components["parameters"]["rowFilter.users.id"];
                    email?: components["parameters"]["rowFilter.users.email"];
                    display_name?: components["parameters"]["rowFilter.users.display_name"];
                    avatar_url?: components["parameters"]["rowFilter.users.avatar_url"];
                    is_onboarded?: components["parameters"]["rowFilter.users.is_onboarded"];
                    raw_user_meta_data?: components["parameters"]["rowFilter.users.raw_user_meta_data"];
                    created_at?: components["parameters"]["rowFilter.users.created_at"];
                    updated_at?: components["parameters"]["rowFilter.users.updated_at"];
                };
                header?: {
                    /** @description Preference */
                    Prefer?: components["parameters"]["preferReturn"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: components["requestBodies"]["users"];
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        users: {
            /**
             * Format: uuid
             * @description Note:
             *     This is a Primary Key.<pk/>
             */
            id: string;
            /** Format: text */
            email?: string;
            /** Format: text */
            display_name?: string;
            /** Format: text */
            avatar_url?: string;
            /**
             * Format: boolean
             * @default false
             */
            is_onboarded: boolean;
            /** Format: jsonb */
            raw_user_meta_data?: unknown;
            /**
             * Format: timestamp with time zone
             * @default now()
             */
            created_at: string;
            /**
             * Format: timestamp with time zone
             * @default now()
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: {
        /** @description Preference */
        preferParams: string;
        /** @description Preference */
        preferReturn: "return=representation" | "return=minimal" | "return=none";
        /** @description Preference */
        preferCount: "count=none";
        /** @description Preference */
        preferPost: "return=representation" | "return=minimal" | "return=none" | "resolution=ignore-duplicates" | "resolution=merge-duplicates";
        /** @description Filtering Columns */
        select: string;
        /** @description On Conflict */
        on_conflict: string;
        /** @description Ordering */
        order: string;
        /** @description Limiting and Pagination */
        range: string;
        /** @description Limiting and Pagination */
        rangeUnit: string;
        /** @description Limiting and Pagination */
        offset: string;
        /** @description Limiting and Pagination */
        limit: string;
        "rowFilter.users.id": string;
        "rowFilter.users.email": string;
        "rowFilter.users.display_name": string;
        "rowFilter.users.avatar_url": string;
        "rowFilter.users.is_onboarded": string;
        "rowFilter.users.raw_user_meta_data": string;
        "rowFilter.users.created_at": string;
        "rowFilter.users.updated_at": string;
    };
    requestBodies: {
        /** @description users */
        users: {
            content: {
                "application/json": components["schemas"]["users"];
                "application/vnd.pgrst.object+json;nulls=stripped": components["schemas"]["users"];
                "application/vnd.pgrst.object+json": components["schemas"]["users"];
                "text/csv": components["schemas"]["users"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
