#!/usr/bin/env sh
set -eu

OUT_DIR="supabase"
OUT_FILE="$OUT_DIR/status.txt"
SCHEMA_FILE="$OUT_DIR/schema.sql"
STORAGE_SCHEMA_FILE="$OUT_DIR/storage_schema.sql"

mkdir -p "$OUT_DIR"
{
  echo "# Generated by supabase status"
  echo "# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  supabase status
} > "$OUT_FILE"

supabase db dump --local --schema public --file "$SCHEMA_FILE"
supabase db dump --local --schema storage --file "$STORAGE_SCHEMA_FILE"
